version: "3"
services:
  mtbexporter:
    restart: unless-stopped
    build: ./
    image: ghcr.io/buschlab/mtbexporter:latest
    command: "/app/settings.yaml"
    volumes:
      - "./settings.yaml:/app/settings.yaml"
      - "./output:/output"
      - "./.state:/.state"
    networks:
      - miracum-cbioportal_cbioportal_net

networks:
  miracum-cbioportal_cbioportal_net:
    external: true