name: Docker Image CI

on:
  push:
    branches: [ latest-docker ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_URL }}/${{ secrets.REPO }}/mtbexporter:latest --label maintainer="Niklas Reimer <${{ secrets.EMAIL }}>"
    - name: Login to Docker registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ secrets.USER }} --password-stdin ${{ secrets.DOCKER_URL }}
    - name: Upload Docker image
      run: docker push ${{ secrets.DOCKER_URL }}/${{ secrets.REPO }}/mtbexporter:latest
